import { Router, type IRouter } from "express";
import healthRouter from "./health";
import animeRouter from "./anime";
import commentsRouter from "./comments";
import communityRouter from "./community";
import discoveryRouter from "./discovery";
import proxyRouter from "./proxy";
import gogoRouter from "./gogo";
import kotoRouter from "./koto";
import mkissaRouter from "./mkissa";
import anizoneRouter from "./anizone";
import miruroRouter from "./miruro";
import comixRouter from "./comix";
import onisagaRouter from "./onisaga";
import viewersRouter from "./viewers";
import votesRouter from "./votes";
import reviewsRouter from "./reviews";
import authRouter from "./auth";
import usersRouter from "./users";
import repliesRouter from "./replies";
import verifyRouter from "./verify";
import translateRouter from "./translate";

const router: IRouter = Router();

router.use(healthRouter);
router.use(animeRouter);
router.use(commentsRouter);
router.use(communityRouter);
router.use(discoveryRouter);
router.use(proxyRouter);
router.use(gogoRouter);
router.use(kotoRouter);
router.use(mkissaRouter);
router.use(anizoneRouter);
router.use(miruroRouter);
router.use(comixRouter);
router.use(onisagaRouter);
router.use(viewersRouter);
router.use(votesRouter);
router.use(reviewsRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(repliesRouter);
router.use(verifyRouter);
router.use(translateRouter);

export default router;
